service: 'accountingapp'
app: account
provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    region: ap-south-1


functions:
  app:
    handler: server.handler
    name: account
    events:
        - http: 
            path: /
            method: ANY
            cors: true
        - http:
            path: /{proxy+}
            method: ANY
            cors: true

plugins: 
  - serverless-dotenv-plugin
